#!/usr/bin/env bash
declare -A solutions=(['raven0']='5' ['raven1']='3' ['raven2']='4' ['raven3']='1' ['raven4']='6' ['raven5']='5' ['raven6']='5' ['raven7']='4' ['raven8']='8' ['raven9']='5' ['raven10']='1' ['raven11']='3' ['raven12']='2' ['raven13']='1' ['raven14']='7' ['raven15']='2' ['raven16']='7' ['raven17']='4' ['raven18']='3' ['raven19']='1' ['raven20']='8' ['raven21']='7' ['raven22']='5' ['raven23']='1' ['raven24']='5')

convert tmp.jpg -resize 400x400\! -flatten -grayscale Rec709Luminance -fuzz 29% +opaque "#000000" tmp.png
bc=$(convert tmp.png -trim -format "%[fx:(1-mean)*w*h]" info:)

num=${1}
s=$(for f in raven*; do
	convert "${f}" -trim -format "%[fx:(1-mean)*w*h]:${f}\n" info:
done | awk -F: -vB="${bc}" '{print abs($1-B)":"$2} function abs(x) { return x < 0 ? -x : x; }' | sort -n -k1 -t: | cut -d: -f2 | sed -n "${num}p")

x=${solutions[${s%.*}]}
eq=$(<formula.txt)
formula=${eq%:*}
diffc=${eq#*:}

for((i=0; i<diffc; i++)); do diffv="diff(${diffv}"; done
diffv+="${formula}"
for((i=0; i<diffc; i++)); do diffv+=")"; done

val=$(qalc -t "${diffv}")
val=$(qalc -t "${val} + x where x=${x}")
case ${val} in
	(*[!0-9]*|"") echo 'Unable to solve' ;;
	*) echo "${val}" ;;
esac
